import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header style={{ backgroundColor: "#fff", display: "flex", justifyContent: "space-between", padding: 20 }}>
          <h1>My Apps</h1>
          <nav
            style={{
              width: "50%",
            }}
          >
            <ul
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                width: "100%",
                height: "100%",
                listStyle: "none",
              }}
            >
              <li>
                <a href="#">Home</a>
              </li>
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Contact</a>
              </li>
            </ul>
          </nav>
        </header>
      </div>

      <div style={{ border: "1px solid black", width: "auto" }}>
        <h1 style={{ textAlign: "center" }}>Ini namanya content</h1>
      </div>
    </>
  );
}
